t0 = 2454966.6983              # time of inferior conjunction
per = 289.863876               # orbital period in days
rp = 0.0275                    # planet radius (in units of stellar radii)
a = 94.4                       # semi-major axis (in units of stellar radii)
inc = 89.76                    # orbital inclination (in degrees)
ecc = 0                        # eccentricity
w = 90                         # longitude of periastron (in degrees)
limb_dark = "quadratic"        # limb darkening model
u = [0.630, 0.076]             # limb darkening coefficients